### ISSUE TITLE
Proper domain name

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicXML2ABCNotationWebApp#26]
The current link http://test-flask.eba-sgnxtm3j.us-east-1.elasticbeanstalk.com/ is not ideal for several reasons:

1) The URL is too long
2) The link's name suggests clearly that this is a tested domain 
3) There are random-looking strings in this domain ("sgnxtm3j")
4) The link exposes our use of elasticbeanstalk

You need to pick a domain name first (let's discuss candidates in this category before you going ahead and purchase one) and re-route this domain to the service you have built. 

I think the documentation here is the right one to look at, please take a look and let's discuss the next steps:

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-beanstalk-environment.html#routing-to-beanstalk-environment-get-domain-name

**Comment by lucien386** [comment]
musicxml2abc.org | Domain registration in progress | July 02, 2020 22:44 UTC-4

**Comment by lucien386** [comment]
http://musicxml2abc.musicalkits.me/
