### ISSUE TITLE
Can i delete certain file change history?

### ISSUE THREAD

**Issue by lucien386** [lucien386/MusicXML2ABCNotationWebApp#38]
In my early development, I mistakenly exposed my aws key in travis.yml. Although it has been ever since encrypted, the original key is still visible from file change history 

https://github.com/lucien386/MusicXML2ABCNotationWebApp/commits/master/.travis.yml

For example,  https://github.com/lucien386/MusicXML2ABCNotationWebApp/blob/f536263931e387598628af5b6dd683f619251a0b/.travis.yml.

Although I have already changed and deleted the exposed key, is there any ways to remove this history?

**Comment by xicheng87** [comment]
Yes you should remove this history as we are open-sourcing the whole project now. Thanks.
