### ISSUE TITLE
Chmod +x on the fly

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicXML2ABCNotationWebApp#44]
Wait a second, I don't think you should do this chmd on the fly. Why can't you change the permission using git?

The point I am trying to make is that you are changing the mode in runtime, but this file is static - this doesn't strike me as the correct approach.

_Originally posted by @xicheng87 in https://github.com/lucien386/MusicXML2ABCNotationWebApp/pull/43_

**Comment by lucien386** [comment]
fixed
