### ISSUE TITLE
Frontend Improvement

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicXML2ABCNotationWebApp#49]
I wonder whether we should follow something shown in this page (https://css-tricks.com/drag-and-drop-file-uploading/) to create a drag-and-drop file uploading flow. The demo (https://css-tricks.com/examples/DragAndDropFileUploading/) looks fairly modern and we can build upon that. 

I recognize that we do have two modes of submitting, one for file and one for plain text. We could create a similar menu bar like shown in the above demo page, one say "upload musicxml file" and the other "paste musicxml directly". 

After accomplishing this step, we then polish the return page. Can you start looking into this? 

Note: in the industry we typically have a designer who does a "mock" of the frontend for developer to use and to implement.

**Comment by lucien386** [comment]
still working on this.. its harder than I thought

**Comment by lucien386** [comment]
Using the code from that website, I am not able to render a new template after uploading the file. The file is successfully uploaded, and the program runs the converter script, but it seems like `render_template` has stopped working

**Comment by lucien386** [comment]
```
return render_template('convert_result.html', 
        task=generate_result(result, converted_text), button_form = ButtonForm())
```

**Comment by lucien386** [comment]
the last line of `converter.py` does not work

**Comment by lucien386** [comment]
https://stackoverflow.com/questions/48015074/flask-render-template-doesnt-work-on-ajax-post this seems to answer my question

**Comment by xicheng87** [comment]
I am still investigating the issue here. I also came across the above post and several other posts after searching in google "Ajax post does not work with Flask". My general understanding is that you have to update the page dynamically once receiving the response of the ajax post based on the response data. Furthermore, I am wondering if the return format from the flask needs to be different for an Ajax post  - I am not sure about it, but it looks that some solution return a son to an Ajax request. 

Need some more time looking into this.

**Comment by xicheng87** [comment]
Haven't yet resolved this issue, I did some debugging and it looks that neither "success" nor "error" call back function gets called (try to redirect to a page like google and you will see that never executes). So basically the ajax put request was sent and received by the flask (I added additional log on the server side and see that the file is correctly received and converted), but somehow flask's return was not received. I tried to reformat flask's return to json but the issue persists. 

Additionally, I find a tutorial talking about how to use ajax to interact with Flask:

https://codehandbook.org/python-flask-jquery-ajax-post/

The code is available here:
https://github.com/jay3dec/PythonFlaskjQueryAjax/tree/master/templates

This is a small code and you may want to clone it and run it locally and see if the ajax function call gets the callback successfully and debug from there. I will also keep looking.

**Comment by lucien386** [comment]
thank you so much! Will look into this tmr
