### ISSUE TITLE
AWS EB cannot locate css/js files

### ISSUE THREAD

**Issue by lucien386** [lucien386/MusicXML2ABCNotationWebApp#54]
everything works locally though

**Comment by lucien386** [comment]
70.19.38.143 (-) - - [17/Jul/2020:02:37:36 +0000] "GET / HTTP/1.1" 200 3833 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
70.19.38.143 (-) - - [17/Jul/2020:02:37:36 +0000] "GET /js/index.js HTTP/1.1" 404 232 "http://musicxml2abc.musicalkits.me/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
70.19.38.143 (-) - - [17/Jul/2020:02:37:36 +0000] "GET /css/index.css HTTP/1.1" 404 232 "http://musicxml2abc.musicalkits.me/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
70.19.38.143 (-) - - [17/Jul/2020:02:37:36 +0000] "GET /css/index.css HTTP/1.1" 404 232 "http://musicxml2abc.musicalkits.me/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
70.19.38.143 (-) - - [17/Jul/2020:02:37:36 +0000] "GET /js/index.js HTTP/1.1" 404 232 "http://musicxml2abc.musicalkits.me/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"

**Comment by xicheng87** [comment]
I don't think the recent fixes resolved this issue. 

So internally, the index.html is located at converter/templates/ , and the js is located at converter/static/js/ , according to the above message and the inspection of the webpage, when the browser tries to fetch index.js is is trying to look at a relative path /js/index.js, so if the index.html is located at the root, this means it is trying to look at converter/templates/js/index.js, which is different from converter/templates/js/index.js, and cannot find it.

**Comment by xicheng87** [comment]
I wonder if it makes sense to move /js and /css to /templates (where index.html) is located and give it a try. Furthermore, I think it is better to rename the js file and css to something more indicative.

**Comment by lucien386** [comment]
still not working after putting a copy of /js and /css under /templates

**Comment by xicheng87** [comment]
Not sure what you meant - I don't see anything merged from the latest pull request, and there is no /js and /css showing up under /templates from master branch it looks like?

**Comment by lucien386** [comment]
its the most recent one

**Comment by lucien386** [comment]
its working now - turns out that i have to change aws eb configuration. I have corrected the static path

**Comment by xicheng87** [comment]
Sounds good, let's do some further backend and frontend cleanup. I think there is still room for improvement of the views. Good job.
