### ISSUE TITLE
bug within music21 itself

### ISSUE THREAD

**Issue by lucien386** [lucien386/MusicXML2ABCNotationWebApp#76]
I have found the problem as to why image conversion is unsuccessful sometimes. See links below: https://www.gitmemory.com/issue/cuthbertLab/music21/419/514631912
https://gitmemory.com/issue/cuthbertLab/music21/419/514706340
`AttributeError: 'Rest' object has no attribute 'hideObjectOnPrint'` is the error message I get every time I encounter this error. Although the developer states that it will be fixed in his next push, at least it persists in my version for now.

**Comment by lucien386** [comment]
So it is fixed in the master branch, which should have included in ver 5.7.2 (which is what I have), but it does not work for me.

**Comment by lucien386** [comment]
i double checked my local music21 lib and this is not fixed yet. The music21 master branch, however, have this fixed.

**Comment by lucien386** [comment]
this is really really weird. I have downloaded version 5.7.2 (proved by using `pip3 show music21`), but when I look into the package code locally the line is still not fixed. But when I look from github release page, the line in ver 5.7.2 is already fixed.

**Comment by xicheng87** [comment]
Well there might have been differences between your download and the github, I suspect that the master branch has not been released. Typically what happen in software development is that you have a "master" branch which includes the latest and greatest, but the  release version is behind because it is meant to be stable and contain less bugs.

**Comment by lucien386** [comment]
anyways, this won't be a problem once I figure out how to get musescore installed on the server
