### ISSUE TITLE
End-to-End Tests

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicXML2ABCNotationWebApp#78]
I kept getting `png file of xml not found. Or file >999 pages?` errors with the files I tried yesterday and some of them worked in the previous version. 

As I mentioned before, we need to add tests to prevent regressions like this. Please add a sufficient of them to ensure the quality. 

I think you need to keep a list of musicxml files in the code base for this purpose.

**Comment by xicheng87** [comment]
Please take this as a priority - keep making changes without adding tests typically degrades software quality. As we are introducing more complexities in the workflow, this becomes increasingly important

**Comment by lucien386** [comment]
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-wsgi'
qt.qpa.screen: QXcbConnection: Could not connect to display 
Could not connect to any X display.
```

**Comment by lucien386** [comment]
I was having this issue before; it can be solved by using `Xvbf`, which works locally - investigating now

**Comment by lucien386** [comment]
fixed - it turns out that I need to set `DISPLAY=:0` as a env variable.
