### ISSUE TITLE
Incorrect music score file

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicXML2ABCNotationWebApp#83]
The output image of this file does not make sense - it seems that it only contains the title of the music but not actual score. 

Overall, please first do more manual testing to ensure that the music score that got output makes sense, and then the sound (midi) files. As I mentioned before, we need to make the current work as stable as possible. 

[ActorPreludeSample.musicxml.zip](https://github.com/lucien386/MusicXML2ABCNotationWebApp/files/4970570/ActorPreludeSample.musicxml.zip)

**Comment by lucien386** [comment]
I have located the problem - its the same as the problem that causes #82
